sudo: false

language: node_js
node_js:
    - "0.12"

addons:
  code_climate:
    repo_token: 01554ef2a9f51ccb9359d5c9af8f935bb604bca187b9df4dfaf3c5d9ba9e9810
      
cache:
  directories:
    - node_modules

after_success:
  - ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
